// Tailadmin/tailadmin-vue-pro-2.0-main/src/views/Tables/BasicTables.vue
<template>
  <AdminLayout>
    <PageBreadcrumb :pageTitle="currentPageTitle" />
    <div class="space-y-5 sm:space-y-6">
      <ComponentCard title="Basic Table 1">
        <BasicTableOne />
      </ComponentCard>
      <ComponentCard title="Basic Table 2">
        <BasicTableTwo />
      </ComponentCard>
      <ComponentCard title="Basic Table 3">
        <BasicTableThree />
      </ComponentCard>
      <ComponentCard title="Basic Table 4">
        <BasicTableFour />
      </ComponentCard>
      <ComponentCard title="Basic Table 5">
        <BasicTableFive />
      </ComponentCard>
    </div>
  </AdminLayout>
</template>

<script setup>
import { ref } from 'vue'
import PageBreadcrumb from '@/components/common/PageBreadcrumb.vue'
import AdminLayout from '@/components/layout/AdminLayout.vue'
import ComponentCard from '@/components/common/ComponentCard.vue'
import BasicTableFive from '@/components/tables/basic-tables/BasicTableFive.vue'
import BasicTableTwo from '@/components/tables/basic-tables/BasicTableTwo.vue'
import BasicTableFour from '@/components/tables/basic-tables/BasicTableFour.vue'
import BasicTableOne from '@/components/tables/basic-tables/BasicTableOne.vue'
import BasicTableThree from '@/components/tables/basic-tables/BasicTableThree.vue'

const currentPageTitle = ref('Basic Tables')
</script>

// Tailadmin/tailadmin-next-typescript-pro-2.0-main/src/app/(admin)/(others-pages)/(tables)/basic-tables/page.tsx
import ComponentCard from "@/components/common/ComponentCard";
import PageBreadcrumb from "@/components/common/PageBreadCrumb";
import BasicTableFive from "@/components/tables/BasicTables/BasicTableFive";
import BasicTableFour from "@/components/tables/BasicTables/BasicTableFour";
import BasicTableOne from "@/components/tables/BasicTables/BasicTableOne";
import BasicTableThree from "@/components/tables/BasicTables/BasicTableThree";
import BasicTableTwo from "@/components/tables/BasicTables/BasicTableTwo";

import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Next.js Basic Data Table | TailAdmin - Next.js Dashboard Template",
  description:
    "This is Next.js Basic Data Table page for TailAdmin - Next.js Tailwind CSS Admin Dashboard Template",
};

export default function BasicTables() {
  return (
    <div>
      <PageBreadcrumb pageTitle="Basic Tables" />
      <div className="space-y-6">
        <ComponentCard title="Basic Table 1">
          <BasicTableOne />
        </ComponentCard>
        <ComponentCard title="Basic Table 2">
          <BasicTableTwo />
        </ComponentCard>
        <ComponentCard title="Basic Table 3">
          <BasicTableThree />
        </ComponentCard>
        <ComponentCard title="Basic Table 4">
          <BasicTableFour />
        </ComponentCard>
        <ComponentCard title="Basic Table 5">
          <BasicTableFive />
        </ComponentCard>
      </div>
    </div>
  );
}
