// Tailadmin/tailadmin-next-typescript-pro-2.0-main/src/app/(admin)/(home)/crm/page.tsx
import CrmMetrics from "@/components/crm/CrmMetrics";
import CrmRecentOrderTable from "@/components/crm/CrmRecentOrderTable";
import CrmStatisticsChart from "@/components/crm/CrmStatisticsChart";
import EstimatedRevenue from "@/components/crm/EstimatedRevenue";
import SalePieChart from "@/components/crm/SalePieChart";
import UpcomingSchedule from "@/components/crm/UpcomingSchedule";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next.js CRM Dashboard | TailAdmin - Next.js Admin Dashboard Template",
  description:
    "This is Next.js CRM Dashboard page for TailAdmin - Next.js Tailwind CSS Admin Dashboard Template",
};

export default function Crm() {
  return (
    <div className="grid grid-cols-12 gap-4 md:gap-6">
      <div className="col-span-12">
        <CrmMetrics />
      </div>

      <div className="col-span-12 xl:col-span-8">
        <CrmStatisticsChart />
      </div>

      <div className="col-span-12 xl:col-span-4">
        <EstimatedRevenue />
      </div>

      <div className="col-span-12 xl:col-span-6">
        <SalePieChart />
      </div>

      <div className="col-span-12 xl:col-span-6">
        <UpcomingSchedule />
      </div>

      <div className="col-span-12">
        <CrmRecentOrderTable />
      </div>
    </div>
  );
}

// Tailadmin/tailadmin-vue-pro-2.0-main/src/views/Crm.vue
<template>
  <admin-layout>
    <div class="grid grid-cols-12 gap-4 md:gap-6">
      <div class="col-span-12">
        <crm-metrics />
      </div>

      <div class="col-span-12 xl:col-span-8">
        <crm-statistics-chart />
      </div>

      <div class="col-span-12 xl:col-span-4">
        <estimated-revenue-chart />
      </div>

      <div class="col-span-12 xl:col-span-6">
        <sale-category-chart />
      </div>

      <div class="col-span-12 xl:col-span-6">
        <upcoming-schedule />
      </div>

      <div class="col-span-12">
        <crm-table />
      </div>
    </div>
  </admin-layout>
</template>

<script>
import CrmMetrics from '../components/crm/CrmMetrics.vue'
import CrmStatisticsChart from '../components/crm/CrmStatisticsChart.vue'
import EstimatedRevenueChart from '../components/crm/EstimatedRevenueChart.vue'
import CrmTable from '../components/crm/CrmTable.vue'
import UpcomingSchedule from '../components/crm/UpcomingSchedule.vue'
import SaleCategoryChart from '../components/crm/SaleCategoryChart.vue'
import AdminLayout from '../components/layout/AdminLayout.vue'
export default {
  components: {
    AdminLayout,
    CrmMetrics,
    EstimatedRevenueChart,
    CrmStatisticsChart,
    CrmTable,
    UpcomingSchedule,
    SaleCategoryChart,
  },
  name: 'Crm',
}
</script>
