// Tailadmin/tailadmin-next-typescript-pro-2.0-main/src/app/(admin)/(home)/marketing/page.tsx
import FeaturedCampaign from "@/components/marketing/FeaturedCampaign";
import ImpressionChart from "@/components/marketing/ImpressionChart";
import MarketingMetricsCards from "@/components/marketing/MarketingMetricsCards";
import TrafficSource from "@/components/marketing/TrafficSource";
import TrafficStats from "@/components/marketing/TrafficStats";
import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title:
    "Next.js Marketing Dashboard | TailAdmin - Next.js Admin Dashboard Template",
  description:
    "This is Next.js Marketing Dashboard page for TailAdmin - Next.js Tailwind CSS Admin Dashboard Template",
};

export default function Marketing() {
  return (
    <div className="grid grid-cols-12 gap-4 md:gap-6">
      <div className="col-span-12">
        <MarketingMetricsCards />
      </div>
      <div className="col-span-12 space-y-6 xl:col-span-8">
        <ImpressionChart />
        <FeaturedCampaign />
      </div>
      <div className="col-span-12 space-y-6 xl:col-span-4">
        <TrafficStats />
        <TrafficSource />
      </div>
    </div>
  );
}

// Tailadmin/tailadmin-vue-pro-2.0-main/src/views/Marketing.vue
<template>
  <admin-layout>
    <div class="grid grid-cols-12 gap-4 md:gap-6">
      <div class="col-span-12">
        <marketing-metrics />
      </div>

      <div class="col-span-12 space-y-6 xl:col-span-8">
        <impression-chart />
        <marketing-table />
      </div>

      <div class="col-span-12 space-y-6 xl:col-span-4">
        <traffic-stats />
        <traffic-source />
      </div>
    </div>
  </admin-layout>
</template>

<script>
import AdminLayout from '../components/layout/AdminLayout.vue'
import MarketingMetrics from '../components/marketing/MarketingMetrics.vue'
import ImpressionChart from '../components/marketing/ImpressionChart.vue'
import TrafficStats from '../components/marketing/TrafficStats.vue'
import TrafficSource from '../components/marketing/TrafficSource.vue'
import MarketingTable from '../components/marketing/MarketingTable.vue'

export default {
  components: {
    AdminLayout,
    MarketingMetrics,
    ImpressionChart,
    TrafficStats,
    TrafficSource,
    MarketingTable,
  },
  name: 'Marketing',
}
</script>
