// Tailadmin/tailadmin-vue-pro-2.0-main/src/views/Stocks.vue
<template>
  <admin-layout>
    <div class="grid grid-cols-12 gap-4 md:gap-6">
      <div class="col-span-12">
        <stocks-metrics />
      </div>

      <div class="col-span-12 space-y-6 xl:col-span-8">
        <portfolio-performance-chart />
        <trending-stocks />
      </div>

      <div class="col-span-12 space-y-6 xl:col-span-4">
        <dividend-chart />
        <my-watch-list />
      </div>

      <div class="col-span-12">
        <stocks-table />
      </div>
    </div>
  </admin-layout>
</template>

<script setup>
import AdminLayout from '../components/layout/AdminLayout.vue'
import StocksMetrics from '../components/stocks/StocksMetrics.vue'
import PortfolioPerformanceChart from '../components/stocks/PortfolioPerformanceChart.vue'
import DividendChart from '../components/stocks/DividendChart.vue'
import MyWatchList from '../components/stocks/Watchlist/MyWatchlist.vue'
import TrendingStocks from '../components/stocks/TrendingStocks.vue'
import StocksTable from '../components/stocks/StocksTable.vue'
</script>

// Tailadmin/tailadmin-next-typescript-pro-2.0-main/src/app/(admin)/(home)/stocks/page.tsx
import DividendChart from "@/components/stocks/DividendChart";
import LatestTransactions from "@/components/stocks/LatestTransactions";
import PortfolioPerformance from "@/components/stocks/PortfolioPerformance";
import StockMetricsList from "@/components/stocks/StockMetricsList";
import TrendingStocks from "@/components/stocks/TrendingStocks";
import WatchList from "@/components/stocks/WatchList";
import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Next.js Stocks Dashboard | TailAdmin - Next.js Dashboard Template",
  description:
    "This is Next.js Stocks Dashboard page for TailAdmin - Next.js Tailwind CSS Admin Dashboard Template",
};
export default function Stocks() {
  return (
    <div className="grid grid-cols-12 gap-4 md:gap-6">
      <div className="col-span-12">
        <StockMetricsList />
      </div>
      <div className="col-span-12 space-y-6 xl:col-span-8">
        <div>
          <PortfolioPerformance />
        </div>
        <TrendingStocks />
      </div>
      <div className="col-span-12 space-y-6 xl:col-span-4">
        <DividendChart />
        <WatchList />
      </div>
      <div className="col-span-12">
        <LatestTransactions />
      </div>
    </div>
  );
}
