// Tailadmin/tailadmin-vue-pro-2.0-main/src/views/Chart/BarChart/BarChart.vue
<template>
  <AdminLayout>
    <PageBreadcrumb :pageTitle="currentPageTitle" />
    <div class="space-y-5 sm:space-y-6">
      <ComponentCard title="Bar Chart 1"> <BarChartOne /> </ComponentCard>
      <ComponentCard title="Bar Chart 2"> <BarChartTwo /> </ComponentCard>
    </div>
  </AdminLayout>
</template>

<script setup>
import BarChartOne from '@/components/charts/BarChart/BarChartOne.vue'
import BarChartTwo from '@/components/charts/BarChart/BarChartTwo.vue'
import ComponentCard from '@/components/common/ComponentCard.vue'
import PageBreadcrumb from '@/components/common/PageBreadcrumb.vue'
import AdminLayout from '@/components/layout/AdminLayout.vue'
import { ref } from 'vue'
const currentPageTitle = ref('Bar Chart')
</script>

// Tailadmin/tailadmin-next-typescript-pro-2.0-main/src/app/(admin)/(others-pages)/(chart)/bar-chart/page.tsx
import BarChartOne from "@/components/charts/bar/BarChartOne";
import BarChartTwo from "@/components/charts/bar/BarChartTwo";
import ComponentCard from "@/components/common/ComponentCard";
import PageBreadcrumb from "@/components/common/PageBreadCrumb";
import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Next.js Bar Chart | TailAdmin - Next.js Dashboard Template",
  description:
    "This is Next.js Bar Chart page for TailAdmin - Next.js Tailwind CSS Admin Dashboard Template",
};

export default function page() {
  return (
    <div>
      <PageBreadcrumb pageTitle="Bar Chart" />
      <div className="space-y-6 overflow-x-hidden">
        <ComponentCard title="Bar Chart 1">
          <BarChartOne />
        </ComponentCard>
        <ComponentCard title="Bar Chart 2">
          <BarChartTwo />
        </ComponentCard>
      </div>
    </div>
  );
}
