// Tailadmin/tailadmin-vue-pro-2.0-main/src/views/Chart/LineChart/LineChart.vue
<template>
  <AdminLayout>
    <PageBreadcrumb :pageTitle="currentPageTitle" />
    <div class="space-y-5 sm:space-y-6">
      <ComponentCard title="Line Chart 1">
        <LineChartOne />
      </ComponentCard>
      <ComponentCard title="Line Chart 2">
        <LineChartTwo />
      </ComponentCard>
      <ComponentCard title="Line Chart 3">
        <LineChartThree />
      </ComponentCard>
    </div>
  </AdminLayout>
</template>

<script setup>
import LineChartOne from '@/components/charts/LineChart/LineChartOne.vue'
import LineChartThree from '@/components/charts/LineChart/LineChartThree.vue'
import LineChartTwo from '@/components/charts/LineChart/LineChartTwo.vue'
import ComponentCard from '@/components/common/ComponentCard.vue'
import PageBreadcrumb from '@/components/common/PageBreadcrumb.vue'
import AdminLayout from '@/components/layout/AdminLayout.vue'
import { ref } from 'vue'
const currentPageTitle = ref('Line Chart')
</script>

// Tailadmin/tailadmin-next-typescript-pro-2.0-main/src/app/(admin)/(others-pages)/(chart)/line-chart/page.tsx
import LineChartOne from "@/components/charts/line/LineChartOne";
import LineChartThree from "@/components/charts/line/LineChartThree";
import LineChartTwo from "@/components/charts/line/LineChartTwo";
import ComponentCard from "@/components/common/ComponentCard";
import PageBreadcrumb from "@/components/common/PageBreadCrumb";
import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Next.js Line Chart | TailAdmin - Next.js Dashboard Template",
  description:
    "This is Next.js Line Chart page for TailAdmin - Next.js Tailwind CSS Admin Dashboard Template",
};
export default function LineChart() {
  return (
    <div>
      <PageBreadcrumb pageTitle="Line Chart" />
      <div className="space-y-6 overflow-x-hidden">
        <ComponentCard title="Line Chart 1">
          <LineChartOne />
        </ComponentCard>
        <ComponentCard title="Line Chart 2">
          <LineChartTwo />
        </ComponentCard>
        <ComponentCard title="Line Chart 3">
          <LineChartThree />
        </ComponentCard>
      </div>
    </div>
  );
}
